package gov.tn.dhs.opa.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-15T19:36:14.387-05:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://oracle.com/determinations/server/12.2.1/rulebase/assess/types", name = "odsAssessServiceGeneric1221_ServiceDelta_type")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OdsAssessServiceGeneric1221ServiceDeltaType {

    @WebMethod(operationName = "ListGoals", action = "http://oracle.com/determinations/server/12.2.1/rulebase/types/ListGoals")
    @WebResult(name = "list-goals-response", targetNamespace = "http://oracle.com/determinations/server/12.2.1/rulebase/assess/types", partName = "ListGoalsResponse")
    public ListGoalsResponse listGoals(

        @WebParam(partName = "ListGoalsRequest", name = "list-goals-request", targetNamespace = "http://oracle.com/determinations/server/12.2.1/rulebase/assess/types")
        ListGoalsRequest listGoalsRequest
    );

    @WebMethod(operationName = "Assess", action = "http://oracle.com/determinations/server/12.2.1/rulebase/types/Assess")
    @WebResult(name = "assess-response", targetNamespace = "http://oracle.com/determinations/server/12.2.1/rulebase/assess/types", partName = "AssessResponse")
    public AssessResponse assess(

        @WebParam(partName = "AssessRequest", name = "assess-request", targetNamespace = "http://oracle.com/determinations/server/12.2.1/rulebase/assess/types")
        AssessRequest assessRequest
    );
}
