package gov.tn.dhs.opa.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-15T19:36:14.396-05:00
 * Generated source version: 3.4.2
 *
 */
@HandlerChain(file="classpath:handler-chain.xml")
@WebServiceClient(name = "odsAssessServiceGeneric1221_ServiceDelta",
                  wsdlLocation = "classpath:service_delta_assess.wsdl",
                  targetNamespace = "http://oracle.com/determinations/server/12.2.1/rulebase/assess/types")
public class OdsAssessServiceGeneric1221ServiceDelta extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://oracle.com/determinations/server/12.2.1/rulebase/assess/types", "odsAssessServiceGeneric1221_ServiceDelta");
    public final static QName OdsAssessServiceGeneric1221ServiceDeltaSOAP = new QName("http://oracle.com/determinations/server/12.2.1/rulebase/assess/types", "odsAssessServiceGeneric1221_ServiceDelta_SOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:service_delta.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OdsAssessServiceGeneric1221ServiceDelta.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:service_delta_assess.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OdsAssessServiceGeneric1221ServiceDelta(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OdsAssessServiceGeneric1221ServiceDelta(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OdsAssessServiceGeneric1221ServiceDelta() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OdsAssessServiceGeneric1221ServiceDelta(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OdsAssessServiceGeneric1221ServiceDelta(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OdsAssessServiceGeneric1221ServiceDelta(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OdsAssessServiceGeneric1221ServiceDeltaType
     */
    @WebEndpoint(name = "odsAssessServiceGeneric1221_ServiceDelta_SOAP")
    public OdsAssessServiceGeneric1221ServiceDeltaType getOdsAssessServiceGeneric1221ServiceDeltaSOAP() {
        return super.getPort(OdsAssessServiceGeneric1221ServiceDeltaSOAP, OdsAssessServiceGeneric1221ServiceDeltaType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OdsAssessServiceGeneric1221ServiceDeltaType
     */
    @WebEndpoint(name = "odsAssessServiceGeneric1221_ServiceDelta_SOAP")
    public OdsAssessServiceGeneric1221ServiceDeltaType getOdsAssessServiceGeneric1221ServiceDeltaSOAP(WebServiceFeature... features) {
        return super.getPort(OdsAssessServiceGeneric1221ServiceDeltaSOAP, OdsAssessServiceGeneric1221ServiceDeltaType.class, features);
    }

}
