
package gov.tn.dhs.opa.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.Authenticator;
import java.net.MalformedURLException;
import java.net.PasswordAuthentication;
import java.net.URL;
import java.util.Map;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Binding;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.EndpointReference;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-15T19:36:14.263-05:00
 * Generated source version: 3.4.2
 *
 */
public final class OdsAssessServiceGeneric1221ServiceDeltaType_OdsAssessServiceGeneric1221ServiceDeltaSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://oracle.com/determinations/server/12.2.1/rulebase/assess/types", "odsAssessServiceGeneric1221_ServiceDelta");

    private OdsAssessServiceGeneric1221ServiceDeltaType_OdsAssessServiceGeneric1221ServiceDeltaSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OdsAssessServiceGeneric1221ServiceDelta.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OdsAssessServiceGeneric1221ServiceDelta ss = new OdsAssessServiceGeneric1221ServiceDelta(wsdlURL, SERVICE_NAME);
        OdsAssessServiceGeneric1221ServiceDeltaType port = ss.getOdsAssessServiceGeneric1221ServiceDeltaSOAP();

        {
        System.out.println("Invoking listGoals...");
        gov.tn.dhs.opa.client.ListGoalsRequest _listGoals_listGoalsRequest = new ListGoalsRequest();
        gov.tn.dhs.opa.client.ListGoalsResponse _listGoals__return = port.listGoals(_listGoals_listGoalsRequest);
        System.out.println("listGoals.result=" + _listGoals__return);
        }

        {
        System.out.println("Invoking assess...");
        gov.tn.dhs.opa.client.AssessRequest _assess_assessRequest = null;
        gov.tn.dhs.opa.client.AssessResponse _assess__return = port.assess(_assess_assessRequest);
        System.out.println("assess.result=" + _assess__return);
        }

        System.exit(0);
    }

}
